"""Add missing columns to users table

Revision ID: 20230723_190943_add_missing_columns
Revises: add_user_rating_fields
Create Date: 2023-07-23 19:09:43.809480
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20230723_190943_add_missing_columns'
down_revision = 'add_user_rating_fields'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем недостающие колонки в таблицу users
    op.add_column('users', sa.Column('reports_count', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('report_category', sa.String(), nullable=True, server_default='normal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'report_category')
    op.drop_column('users', 'reports_count')
    # ### end Alembic commands ###