"""Rating system enhancements

Revision ID: 20240520_rating_system_enhancements
Revises: initial
Create Date: 2024-05-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20240520_rating_system_enhancements'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем колонки, если их нет
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'user_rating' not in columns:
        op.add_column('users', sa.Column('user_rating', sa.Integer(), nullable=True, server_default='100'))
    
    if 'profile_completed' not in columns:
        op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True, server_default='0'))
    
    # Обновляем значения по умолчанию для полей рейтинга
    op.execute("UPDATE users SET user_rating = 100 WHERE user_rating IS NULL")
    op.execute("UPDATE users SET profile_completed = 0 WHERE profile_completed IS NULL")
    
    # Обновляем статус заполнения профиля для всех пользователей
    op.execute("""
    UPDATE users 
    SET profile_completed = 
        CASE 
            WHEN first_name IS NOT NULL AND first_name != '' AND
                 age IS NOT NULL AND
                 gender IS NOT NULL AND gender != '' AND
                 orientation IS NOT NULL AND orientation != '' AND
                 city IS NOT NULL AND city != '' AND
                 bio IS NOT NULL AND bio != '' AND
                 photo_id IS NOT NULL AND photo_id != '' AND
                 tags IS NOT NULL AND tags != ''
            THEN 1
            ELSE 0
        END
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'user_rating')
    # ### end Alembic commands ###