"""Add user rating fields

Revision ID: add_user_rating_fields
Revises: initial
Create Date: 2023-07-24 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_user_rating_fields'
down_revision = 'initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_rating', sa.Integer(), nullable=True, server_default='100'))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'user_rating')
    # ### end Alembic commands ###